[package]
name = "YTD"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustube = "0.6.0"
gtk = "0.18.1"
tokio = "1.36.0"
full = "0.1.0"
